import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { useAuthContext } from '@/providers/AuthProvider';
import { Header } from '@/components/Header';

import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { auth, db } from '../firebase';

export default function Chat(): JSX.Element {
  const { user } = useAuthContext();
  const router = useRouter();

  console.log('tweet' + user);

  const [twtext, setTwtext] = useState('');
  const twTextWriting = (e) => {
    setTwtext(e.target.value);
  };
  console.log(auth.currentUser);
  const sendPost = async () => {
    await addDoc(collection(db, 'tweets'), {
      createdAt: serverTimestamp(),
      twText: twtext,
      user: {
        name: auth.currentUser.displayName,
        id: auth.currentUser.uid,
        photoURL: auth.currentUser.photoURL,
      },
    });
    router.push('/');
  };
  return (
    <div>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="home">
        <h1>Chat</h1>
        {/* {twtext} */}
        <p>
          <input onChange={twTextWriting} type="text" placeholder="Lets Tweet!" />
        </p>
        <p>
          <button onClick={sendPost}>Tweetする</button>
        </p>
      </div>
    </div>
  );
}
