import Head from 'next/head';
import { useRouter } from 'next/router';
import { useContext } from 'react';
import { IsAuthContext } from '@/providers/IsAuthProvider';
import Header from '@/components/Header';

import { GoogleAuthProvider, signInWithPopup } from 'firebase/auth';
import { auth } from '../firebase';
const provider = new GoogleAuthProvider();

export default function Login() {
  const { isAuth, setIsAuth } = useContext(IsAuthContext);
  const router = useRouter();

  console.log('ログインCOMP最初' + isAuth);
  const loginWithGoogle = async () => {
    try {
      const { user } = await signInWithPopup(auth, provider);
      console.log(isAuth);
      setIsAuth(true);
      router.push('/');
      console.log({ uid: user.uid, displayName: user.displayName });
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="home">
        <h1>ログイン</h1>
        <p>ログインしてください</p>
        <button onClick={loginWithGoogle}>Googleログイン</button>
      </div>
    </div>
  );
}
